---
reverse_proxy_cert_fullchain: "/var/lib/dehydrated/certs/{{ public_domain }}/fullchain.pem"
reverse_proxy_cert_privkey: "/var/lib/dehydrated/certs/{{ public_domain }}/privkey.pem"
reverse_proxy_acme_webroot: /var/lib/dehydrated/acme-challenges
