// The printed document stays English: the PDF renders trial text as stored, not as translated.
export const PRINT_DOC = {
  brand: 'Camille, the Cancer Trial Chatbot',
  eyebrow: 'Trial summary',
  generatedLabel: 'Generated',
  sitesLabel: 'Sites',
  aboutLabel: 'About this trial',
  inclusionLabel: 'Who can join',
  exclusionLabel: 'Who cannot join',
  watermark: 'Camille',
  footerLead: 'This summary was generated by Camille, the Cancer Trial Chatbot:',
  dataCheckpoint: 'Trial data last checked',
} as const;
