"""add trials.disease_stages

Revision ID: 57bbd3a0f8a0
Revises: a1a6f7e73aeb
Create Date: 2026-08-27 19:18:57.160328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "57bbd3a0f8a0"
down_revision: str | None = "a1a6f7e73aeb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trials",
        sa.Column(
            "disease_stages", sa.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trials", "disease_stages")
    # ### end Alembic commands ###
