"""add data schema

Revision ID: a90b558a91dc
Revises: 26b6068ec3fe
Create Date: 2026-05-30 21:24:31.520744

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a90b558a91dc'
down_revision: str | None = '26b6068ec3fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('name_fr', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lon', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_city', 'locations', ['city'], unique=False)
    op.create_index('ix_locations_city_province', 'locations', ['city', 'province'], unique=False)
    op.create_index('ix_locations_province', 'locations', ['province'], unique=False)
    op.create_table('trials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('acronym_or_protocol_id', sa.Text(), nullable=True),
    sa.Column('nct_number', sa.Text(), nullable=True),
    sa.Column('short_title_en', sa.Text(), nullable=True),
    sa.Column('short_title_fr', sa.Text(), nullable=True),
    sa.Column('official_title_en', sa.Text(), nullable=True),
    sa.Column('official_title_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('inclusion_criteria_en', sa.Text(), nullable=True),
    sa.Column('inclusion_criteria_fr', sa.Text(), nullable=True),
    sa.Column('exclusion_criteria_en', sa.Text(), nullable=True),
    sa.Column('exclusion_criteria_fr', sa.Text(), nullable=True),
    sa.Column('phases', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('treatment_type_names', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('intervention_names', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('treatment_lines', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('study_type', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('sponsor_name', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trials_intervention_names_gin', 'trials', ['intervention_names'], unique=False, postgresql_using='gin')
    op.create_index('ix_trials_phases_gin', 'trials', ['phases'], unique=False, postgresql_using='gin')
    op.create_index('ix_trials_treatment_type_names_gin', 'trials', ['treatment_type_names'], unique=False, postgresql_using='gin')
    op.create_table('trial_sites',
    sa.Column('trial_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('cancer_type_names', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trial_id', 'location_id')
    )
    op.create_index('ix_trial_sites_cancer_type_names_gin', 'trial_sites', ['cancer_type_names'], unique=False, postgresql_using='gin')
    op.create_index('ix_trial_sites_state', 'trial_sites', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trial_sites_state', table_name='trial_sites')
    op.drop_index('ix_trial_sites_cancer_type_names_gin', table_name='trial_sites', postgresql_using='gin')
    op.drop_table('trial_sites')
    op.drop_index('ix_trials_treatment_type_names_gin', table_name='trials', postgresql_using='gin')
    op.drop_index('ix_trials_phases_gin', table_name='trials', postgresql_using='gin')
    op.drop_index('ix_trials_intervention_names_gin', table_name='trials', postgresql_using='gin')
    op.drop_table('trials')
    op.drop_index('ix_locations_province', table_name='locations')
    op.drop_index('ix_locations_city_province', table_name='locations')
    op.drop_index('ix_locations_city', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
