"""add openai embedding column

Revision ID: 08ccc8dcbba5
Revises: a256c203090a
Create Date: 2026-06-15 21:36:46.959555

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '08ccc8dcbba5'
down_revision: str | None = 'a256c203090a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('embedding_openai', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'embedding_openai')
    # ### end Alembic commands ###
