"""add trial source provenance and age range

Revision ID: 2bb059424560
Revises: 06cdb51f66a7
Create Date: 2026-09-09 21:28:59.754508

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bb059424560'
down_revision: str | None = '06cdb51f66a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trial_sites', sa.Column('data_sources', sa.ARRAY(sa.Text()), server_default='{ctc}', nullable=False))
    op.create_index('ix_trial_sites_data_sources_gin', 'trial_sites', ['data_sources'], unique=False, postgresql_using='gin')
    op.add_column('trials', sa.Column('age_range_text', sa.Text(), nullable=True))
    op.add_column('trials', sa.Column('source_keys', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###

    # Every existing trial is CTC, keyed by the protocol id its public URL uses.
    op.execute(
        """
        UPDATE trials
        SET source_keys = jsonb_build_object('ctc', acronym_or_protocol_id)
        WHERE acronym_or_protocol_id IS NOT NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'source_keys')
    op.drop_column('trials', 'age_range_text')
    op.drop_index('ix_trial_sites_data_sources_gin', table_name='trial_sites', postgresql_using='gin')
    op.drop_column('trial_sites', 'data_sources')
    # ### end Alembic commands ###
