"""drop french columns, add trial source_updated_at

Revision ID: a1a6f7e73aeb
Revises: 68be567bc8ae
Create Date: 2026-08-27 11:36:18.454161

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a1a6f7e73aeb'
down_revision: str | None = '68be567bc8ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'name_fr')
    op.add_column('trials', sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_trials_source_updated_at', 'trials', ['source_updated_at'], unique=False)
    op.drop_column('trials', 'exclusion_criteria_fr')
    op.drop_column('trials', 'inclusion_criteria_fr')
    op.drop_column('trials', 'description_fr')
    op.drop_column('trials', 'official_title_fr')
    op.drop_column('trials', 'short_title_fr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('short_title_fr', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trials', sa.Column('official_title_fr', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trials', sa.Column('description_fr', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trials', sa.Column('inclusion_criteria_fr', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trials', sa.Column('exclusion_criteria_fr', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_trials_source_updated_at', table_name='trials')
    op.drop_column('trials', 'source_updated_at')
    op.add_column('locations', sa.Column('name_fr', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
