"""add trial site coordinators

Revision ID: 4ac34d941343
Revises: 92662f7cd13a
Create Date: 2026-08-31 13:00:35.636998

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ac34d941343"
down_revision: str | None = "92662f7cd13a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trial_sites",
        sa.Column(
            "coordinators",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trial_sites", "coordinators")
    # ### end Alembic commands ###
