"""add trials.trial_ref identity

Revision ID: 92662f7cd13a
Revises: 57bbd3a0f8a0
Create Date: 2026-08-28 12:24:01.922904

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '92662f7cd13a'
down_revision: str | None = '57bbd3a0f8a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_LENGTH = 8
# Inlined rather than imported: a migration must keep working even after
# schemas/trial_ref.py changes. Keep the two in step.
_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def _ref(trial_id: uuid.UUID) -> str:
    bits = trial_id.int >> (128 - 5 * _LENGTH)
    return "CTC-" + "".join(
        _ALPHABET[(bits >> (5 * i)) & 0x1F] for i in reversed(range(_LENGTH))
    )


def upgrade() -> None:
    op.add_column('trials', sa.Column('trial_ref', sa.Text(), nullable=True))
    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id FROM trials")).fetchall()
    for (trial_id,) in rows:
        bind.execute(
            sa.text("UPDATE trials SET trial_ref = :ref WHERE id = :id"),
            {"ref": _ref(trial_id), "id": trial_id},
        )
    op.alter_column('trials', 'trial_ref', nullable=False)
    op.create_index(op.f('ix_trials_nct_number'), 'trials', ['nct_number'], unique=False)
    op.create_index(op.f('ix_trials_trial_ref'), 'trials', ['trial_ref'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trials_trial_ref'), table_name='trials')
    op.drop_index(op.f('ix_trials_nct_number'), table_name='trials')
    op.drop_column('trials', 'trial_ref')
    # ### end Alembic commands ###
