from enum import StrEnum

CancerType = StrEnum(
    "CancerType",
    {
        "Anal Cancer": "Anal Cancer",
        "Bile Duct Cancer": "Bile Duct Cancer",
        "Biliary Tract Cancer": "Biliary Tract Cancer",
        "Bladder Cancer": "Bladder Cancer",
        "Brain Cancer": "Brain Cancer",
        "Breast Cancer": "Breast Cancer",
        "Cervix Cancer": "Cervix Cancer",
        "Colorectal Cancer": "Colorectal Cancer",
        "Endocrine": "Endocrine",
        "Endometrial cancer": "Endometrial cancer",
        "Esophageal Cancer": "Esophageal Cancer",
        "Gastric Cancer": "Gastric Cancer",
        "Gastrointestinal Cancer": "Gastrointestinal Cancer",
        "Genitourinary Cancer": "Genitourinary Cancer",
        "Gynecologic cancer": "Gynecologic cancer",
        "Head and Neck": "Head and Neck",
        "Hematological Cancer": "Hematological Cancer",
        "Hematopoietic System": "Hematopoietic System",
        "Kidney Cancer": "Kidney Cancer",
        "Larynx Cancer": "Larynx Cancer",
        "Leukemia": "Leukemia",
        "Liver Cancer": "Liver Cancer",
        "Lung Cancer": "Lung Cancer",
        "Lymphoma": "Lymphoma",
        "Melanoma": "Melanoma",
        "Myelodysplastic Syndromes (MDS)": "Myelodysplastic Syndromes (MDS)",
        "Myeloma": "Myeloma",
        "Myeloproliferative Neoplasms (MPN)": "Myeloproliferative Neoplasms (MPN)",
        "Nasopharyngeal Cancer": "Nasopharyngeal Cancer",
        "Neuroblastoma": "Neuroblastoma",
        "Neuroendocrine Tumors": "Neuroendocrine Tumors",
        "Oropharyngeal Cancer": "Oropharyngeal Cancer",
        "Other": "Other",
        "Ovarian Cancer": "Ovarian Cancer",
        "Pancreatic Cancer": "Pancreatic Cancer",
        "Peritoneal Cancer": "Peritoneal Cancer",
        "Prostate Cancer": "Prostate Cancer",
        "Salivary Glands": "Salivary Glands",
        "Sarcoma": "Sarcoma",
        "Skin Cancer": "Skin Cancer",
        "Solid Tumors": "Solid Tumors",
        "Testicular Cancer": "Testicular Cancer",
        "Thyroid Cancer": "Thyroid Cancer",
        "Treatments and side effects": "Treatments and side effects",
        "Urothelial Cancer": "Urothelial Cancer",
        "Uterine Cancer": "Uterine Cancer",
        "Vulvar Cancer": "Vulvar Cancer",
    },
)
